import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const dataFile = path.join(__dirname, 'src', 'data', 'sessionsData.json');

const quizzes = {
  "3-9": [
    { id: 1, question: "¿Qué tipo de aprendizaje es K-Means Clustering (Agrupamiento)?", options: ["Aprendizaje Supervisado", "Aprendizaje No Supervisado (los datos no tienen etiquetas previas)", "Aprendizaje por Refuerzo", "Deep Learning"], correctAnswer: 1 },
    { id: 2, question: "¿Cuál es el objetivo principal de un algoritmo de Clustering como K-Means?", options: ["Adivinar el futuro", "Agrupar puntos de datos similares en 'K' grupos (clusters) distintos basándose en sus características", "Dibujar líneas rectas", "Traducir textos"], correctAnswer: 1 },
    { id: 3, question: "¿Qué es un 'Centroide' en K-Means?", options: ["Un tipo de robot", "El punto central (media matemática) de todos los puntos de datos que pertenecen a un cluster específico", "El margen de error", "Un punto atípico"], correctAnswer: 1 },
    { id: 4, question: "¿Cómo se asigna un punto a un cluster durante el algoritmo?", options: ["Al azar", "Se asigna al cluster cuyo Centroide esté más cerca (generalmente distancia euclidiana)", "Se le asigna al último cluster creado", "Por votación de árboles"], correctAnswer: 1 },
    { id: 5, question: "¿Qué significa la 'K' en K-Means?", options: ["Kilogramos", "El número fijo de clusters (grupos) que le decimos al algoritmo que debe buscar", "Una constante matemática", "K-vecinos"], correctAnswer: 1 },
    { id: 6, question: "¿Cuál es el principal reto o problema de K-Means?", options: ["Es muy lento computacionalmente", "Debemos elegir o adivinar el número 'K' de antemano y es sensible a la posición inicial aleatoria de los centroides", "No funciona con números", "Solo funciona en Deep Learning"], correctAnswer: 1 },
    { id: 7, question: "¿Qué técnica se usa comúnmente para determinar el número óptimo de 'K'?", options: ["El método del codo (Elbow Method)", "Lanzar un dado", "Regla de Bayes", "Descenso del gradiente"], correctAnswer: 0 }
  ],
  "3-10": [
    { id: 1, question: "¿Qué es la Reducción de Dimensionalidad?", options: ["Bajar la resolución de una pantalla", "El proceso de reducir el número de características (variables o columnas) aleatorias bajo consideración, obteniendo un conjunto de variables principales", "Borrar filas del dataset", "Hacer el código más corto"], correctAnswer: 1 },
    { id: 2, question: "¿Qué es 'La Maldición de la Dimensionalidad' (Curse of Dimensionality)?", options: ["Un hechizo de videojuego", "El fenómeno donde al aumentar muchas variables (dimensiones), los datos se vuelven tan dispersos que la distancia entre puntos pierde sentido y los modelos fallan", "Un error de sintaxis", "Que los datos ocupan mucho espacio en el monitor"], correctAnswer: 1 },
    { id: 3, question: "¿Cuál es el algoritmo más famoso y usado para Reducción de Dimensionalidad?", options: ["SVM", "PCA (Principal Component Analysis / Análisis de Componentes Principales)", "Árboles de decisión", "K-Means"], correctAnswer: 1 },
    { id: 4, question: "¿Cómo funciona internamente PCA a nivel conceptual?", options: ["Borra columnas al azar", "Rota los ejes de los datos para encontrar nuevas dimensiones (Componentes Principales) que maximizan la varianza (información) original", "Combina todas las columnas en una sola suma", "Transforma números a texto"], correctAnswer: 1 },
    { id: 5, question: "Si reducimos de 100 características a solo 2 Componentes Principales con PCA, ¿qué ganancia inmediata obtenemos?", options: ["Podemos visualizar los datos en un gráfico 2D", "El modelo se vuelve 100 veces más exacto", "Perdemos toda la información obligatoriamente", "Ganamos dinero"], correctAnswer: 0 },
    { id: 6, question: "¿Las nuevas variables (Componentes Principales) generadas por PCA mantienen el significado original (ej. 'Precio' o 'Edad')?", options: ["Sí, son exactamente iguales", "No, son combinaciones matemáticas lineales abstractas de las originales, perdiendo interpretabilidad humana directa", "Solo si se cambian los nombres", "Depende de la computadora"], correctAnswer: 1 },
    { id: 7, question: "¿PCA es un algoritmo supervisado o no supervisado?", options: ["Supervisado, requiere etiquetas", "No supervisado, solo analiza la estructura y varianza de los datos de entrada X", "Por refuerzo", "Semi-supervisado"], correctAnswer: 1 }
  ],
  "3-11": [
    { id: 1, question: "¿Cuál es la diferencia principal entre Selección de Características (Feature Selection) y Reducción de Dimensionalidad (como PCA)?", options: ["Son lo mismo", "La Selección elige las mejores variables originales y descarta el resto; PCA crea variables nuevas matemáticas combinando las originales", "Selección es para texto y PCA para números", "Selección es más lenta"], correctAnswer: 1 },
    { id: 2, question: "¿Por qué querríamos descartar algunas características de nuestros datos?", options: ["Porque tenemos mucha memoria RAM", "Para simplificar el modelo, reducir sobreajuste (overfitting), acelerar el entrenamiento e ignorar variables irrelevantes o ruidosas", "Para que los datos quepan en un disquete", "Por cuestiones estéticas"], correctAnswer: 1 },
    { id: 3, question: "¿Qué son los 'Filtros' (Filter Methods) en Feature Selection?", options: ["Un filtro de Instagram", "Técnicas estadísticas simples (como la correlación de Pearson o prueba Chi-Cuadrado) que puntúan la importancia de cada variable independientemente del modelo", "Redes neuronales complejas", "Filtros de Spam"], correctAnswer: 1 },
    { id: 4, question: "¿Qué significa que dos características (features) estén altamente correlacionadas entre sí (Colinealidad)?", options: ["Que son la misma característica", "Que aportan básicamente la misma información redundante, por lo que a menudo podemos descartar una de las dos", "Que son muy importantes y debemos multiplicarlas", "Que el modelo colapsará"], correctAnswer: 1 },
    { id: 5, question: "¿Qué son los 'Métodos Embebidos' (Embedded Methods)?", options: ["Hardware", "Algoritmos que seleccionan características durante su propio proceso de entrenamiento, como la Regularización L1 (Lasso) o la importancia de características en Random Forest", "Bases de datos SQL", "Modelos que se ejecutan en navegadores"], correctAnswer: 1 },
    { id: 6, question: "En un Random Forest, ¿podemos saber qué características fueron más importantes para el modelo final?", options: ["No, es una caja negra impenetrable", "Sí, Scikit-learn nos provee el atributo 'feature_importances_' para ver cuánto contribuyó cada variable a las decisiones", "Solo pagando la versión premium", "Solo si es un bosque pequeño"], correctAnswer: 1 },
    { id: 7, question: "¿Qué son los métodos 'Wrapper' (Envoltura)?", options: ["Papel para regalo", "Algoritmos que evalúan múltiples subconjuntos de características entrenando un modelo para cada subconjunto (ej. RFE - Recursive Feature Elimination)", "Librerías de CSS", "Archivos empaquetados .tar"], correctAnswer: 1 }
  ],
  "3-12": [
    { id: 1, question: "En problemas de Clasificación, ¿qué es la 'Accuracy' (Exactitud)?", options: ["El porcentaje de veces que el modelo acertó (Predicciones Correctas / Total de Predicciones)", "La exactitud de los tipos de datos en la memoria", "La velocidad a la que procesa los datos", "El número de capas de una red"], correctAnswer: 0 },
    { id: 2, question: "¿Cuándo la 'Accuracy' (Exactitud) es una métrica engañosa y PELIGROSA?", options: ["Cuando hay pocos datos", "Cuando las clases están altamente desbalanceadas (ej. 99% transacciones normales, 1% fraudes). Un modelo que siempre dice 'Normal' tendría 99% de accuracy pero sería inútil", "Cuando el modelo es muy profundo", "Nunca es engañosa"], correctAnswer: 1 },
    { id: 3, question: "¿Qué es la 'Precisión' (Precision)?", options: ["De todas las veces que el modelo predijo POSITIVO, ¿cuántas fueron realmente POSITIVO? (Mide la calidad y evita falsos positivos)", "El número de decimales que usa Python", "La exactitud total", "El porcentaje de errores"], correctAnswer: 0 },
    { id: 4, question: "¿Qué es el 'Recall' (Sensibilidad o Exhaustividad)?", options: ["De todos los positivos REALES que existen, ¿cuántos logró encontrar el modelo? (Evita los falsos negativos)", "Recordar los datos borrados", "Recargar la página web", "Llamar a una función de nuevo"], correctAnswer: 0 },
    { id: 5, question: "Si estamos creando un modelo para detectar Cáncer, ¿qué métrica es absolutamente crítica maximizar para no mandar pacientes enfermos a casa (evitar falsos negativos)?", options: ["Accuracy", "Precisión (Precision)", "Recall (Sensibilidad)", "R2"], correctAnswer: 2 },
    { id: 6, question: "Si estamos creando un filtro de Spam de correo, y no queremos que un correo urgente de trabajo se vaya a Spam (Falso Positivo), ¿qué métrica priorizamos?", options: ["Recall", "Precisión (Precision)", "Error Absoluto Medio", "Ninguna"], correctAnswer: 1 },
    { id: 7, question: "¿Qué curva se usa gráficamente para evaluar el rendimiento de un clasificador binario a medida que variamos su umbral de decisión?", options: ["Curva de Gauss", "Curva ROC (Receiver Operating Characteristic) y su área AUC", "Curva de demanda", "Curva de Aprendizaje"], correctAnswer: 1 }
  ],
  "3-13": [
    { id: 1, question: "En modelos de Regresión (que predicen números), ¿por qué no podemos usar 'Accuracy' o la Matriz de Confusión?", options: ["Porque es aburrido", "Porque las predicciones casi nunca serán idénticas al decimal exacto real; medimos la DISTANCIA del error, no si acertó exactamente la categoría", "Porque las librerías no lo permiten", "Porque son números impares"], correctAnswer: 1 },
    { id: 2, question: "¿Qué significa MAE (Mean Absolute Error)?", options: ["El promedio del valor absoluto de los errores entre las predicciones y los reales. Es intuitivo y está en la misma unidad que el objetivo", "Un error máximo", "El error del error", "Multilayer Absolute Engine"], correctAnswer: 0 },
    { id: 3, question: "¿Qué hace la métrica MSE (Mean Squared Error) diferente del MAE?", options: ["Divide todo por dos", "Eleva los errores al cuadrado antes de promediar, penalizando MUCHO más a los errores grandes (outliers)", "Toma la raíz cuadrada", "Es exclusiva para textos"], correctAnswer: 1 },
    { id: 4, question: "¿Qué es RMSE (Root Mean Squared Error)?", options: ["La raíz cuadrada del MSE, lo cual devuelve la métrica a las unidades originales de los datos, siendo la métrica de regresión más estándar", "Una métrica de enrutamiento", "Routing Mean System Error", "La división por cero"], correctAnswer: 0 },
    { id: 5, question: "¿Qué nos indica un valor R² (R-Cuadrado) cercano a 1 (o 100%)?", options: ["Que el modelo es el peor posible", "Que el modelo explica perfectamente la varianza de los datos (las predicciones encajan perfectamente con los reales)", "Que hay un error de sintaxis", "Que la computadora se trabó"], correctAnswer: 1 },
    { id: 6, question: "¿Qué nos indica un valor R² igual a 0?", options: ["Un modelo excelente", "Que nuestro modelo es igual de inútil que simplemente predecir siempre el promedio de los datos", "Que faltan datos", "Que la memoria está llena"], correctAnswer: 1 },
    { id: 7, question: "¿Qué es la 'Validación Cruzada' (K-Fold Cross Validation)?", options: ["Cruzar los dedos para que funcione", "Dividir el dataset en 'K' pliegues, entrenando y probando el modelo múltiples veces rotando el set de prueba para obtener un promedio realista del rendimiento", "Validar los datos usando contraseñas cruzadas", "Una métrica de clasificación"], correctAnswer: 1 }
  ],
  "3-14": [
    { id: 1, question: "¿Qué distingue al Aprendizaje No Supervisado del Supervisado?", options: ["Es más caro", "El algoritmo se alimenta con datos SIN ETIQUETAR, debiendo encontrar patrones o estructuras ocultas por sí mismo", "Usa redes neuronales", "No requiere matemáticas"], correctAnswer: 1 },
    { id: 2, question: "¿Cuál es una técnica clásica de Aprendizaje No Supervisado para agrupar clientes?", options: ["Regresión Lineal", "Random Forest", "Clustering (como K-Means o DBSCAN)", "Descenso de gradiente"], correctAnswer: 2 },
    { id: 3, question: "¿Qué es la 'Detección de Anomalías' (Outlier Detection) en el contexto no supervisado?", options: ["Encontrar errores de sintaxis", "Identificar puntos de datos raros o sospechosos que difieren significativamente de la mayoría (ej. fraude bancario) sin tener ejemplos previos etiquetados de fraude", "Borrar carpetas", "Predecir números"], correctAnswer: 1 },
    { id: 4, question: "¿Qué son las 'Reglas de Asociación' (ej. Algoritmo Apriori)?", options: ["Reglas de un club", "Técnicas que descubren qué artículos se compran frecuentemente juntos (ej. 'Quien compró pañales, también compró cerveza')", "Reglas gramaticales", "Reglas matemáticas de derivación"], correctAnswer: 1 },
    { id: 5, question: "Además de Clustering, ¿qué otra gran familia pertenece al aprendizaje no supervisado?", options: ["Clasificación binaria", "Reducción de Dimensionalidad (como PCA)", "Regresión múltiple", "Validación cruzada"], correctAnswer: 1 },
    { id: 6, question: "¿Qué es el Clustering Jerárquico?", options: ["Un agrupamiento para jefes y empleados", "Un algoritmo que construye una jerarquía de agrupamientos que se puede visualizar como un árbol llamado 'Dendrograma'", "Un tipo de base de datos", "Un método de ordenamiento"], correctAnswer: 1 },
    { id: 7, question: "¿Cómo validas usualmente si un modelo no supervisado 'lo hizo bien'?", options: ["Comparando con las etiquetas Accuracy", "Calculando el MSE", "Es muy difícil y subjetivo; a menudo requiere inspección visual, análisis de negocio (Silhouette Score) o expertos de dominio", "Mirando si el código compiló"], correctAnswer: 2 }
  ],
  "3-15": [
    { id: 1, question: "En un proyecto completo de Machine Learning, ¿cuál es el paso más importante que define el éxito antes de tocar una línea de código?", options: ["Instalar Python", "Entender y definir claramente el Problema de Negocio y las métricas de éxito", "Comprar una GPU", "Crear una página web"], correctAnswer: 1 },
    { id: 2, question: "Después de definir el problema, ¿cuál suele ser el siguiente gran paso?", options: ["Entrenar una Red Neuronal Profunda", "Recopilar y Explorar los Datos (EDA) para entender su distribución y problemas", "Desplegar a producción", "Generar un reporte PDF"], correctAnswer: 1 },
    { id: 3, question: "¿Por qué dividimos SIEMPRE nuestros datos en Train (Entrenamiento) y Test (Prueba) al inicio del modelado?", options: ["Para no quedarnos sin memoria RAM", "Para poder evaluar de forma honesta si el modelo puede generalizar a datos nuevos que NUNCA ha visto", "Para tener copias de seguridad", "Por orden alfabético"], correctAnswer: 1 },
    { id: 4, question: "¿Qué es un 'Baseline Model' (Modelo Base o de Referencia)?", options: ["El modelo de Inteligencia Artificial más complejo", "Un modelo muy simple (ej. Regresión Lineal básica o predecir siempre la media) que sirve como punto de partida para ver si nuestros modelos complejos realmente aportan valor", "Un modelo que no usa código", "Un sistema de bases de datos"], correctAnswer: 1 },
    { id: 5, question: "¿Qué proceso realizamos sistemáticamente para mejorar el rendimiento de nuestro modelo elegido?", options: ["Pintar los gráficos", "Ajuste de Hiperparámetros (Hyperparameter Tuning), por ejemplo usando GridSearch o RandomSearch", "Reiniciar la computadora muchas veces", "Cambiar los nombres de las variables"], correctAnswer: 1 },
    { id: 6, question: "Si has terminado el proyecto y tu modelo predice muy bien, ¿cuál es el último paso fundamental en la industria?", options: ["Imprimir el código", "Desplegar el modelo a Producción (ej. mediante una API REST con FastAPI o Flask) para que otros sistemas o usuarios puedan consumirlo", "Borrar los datos de entrenamiento", "Vender el código fuente"], correctAnswer: 1 },
    { id: 7, question: "¿Por qué es crucial la 'Comunicación' en un proyecto de ciencia de datos?", options: ["Para chatear con otros programadores", "Porque el mejor modelo del mundo es inútil si los directivos (stakeholders) no confían en él o no entienden sus resultados y limitaciones", "Para usar más palabras", "Para escribir correos electrónicos"], correctAnswer: 1 }
  ]
};

const data = JSON.parse(fs.readFileSync(dataFile, 'utf8'));
data.forEach(session => {
  if (quizzes[session.id]) {
    session.quiz = quizzes[session.id];
  }
});
fs.writeFileSync(dataFile, JSON.stringify(data, null, 2));
console.log('Successfully updated Mod 3 Part 2');
